### ISSUE TITLE
如何携带数据发送信息

### ISSUE THREAD

**Issue by qlang122** [fengzhizi715/EventBus#2]
如标题，发消息，大多数时候无非是为了替代广播等不能携带大数据的问题，现在如果需要带数据咋办？

**Comment by fengzhizi715** [comment]
hi 不好意思才看到
携带消息其实很简单，定义一个形如：
class ScreenOrientationEvent(var screenOrientation:String)

然后在某个地方进行订阅：
    @Subscribe
    fun screenOrientation(event: ScreenOrientationEvent) {
           ......
    }
